### PR TITLE
Bundle in a certificate authority file

### PR DESCRIPTION
**Pull request by guywithnose**
The file included with Guzzle 3 is too old

### CODE REVIEW

**Comment by guywithnose** [comment]
This is the best I could come up with, but I'm open to other options.

**Comment by nubs** [comment]
What about upgrading guzzle?

**Comment by guywithnose** [comment]
https://github.com/KnpLabs/php-github-api/issues/157

**Comment by guywithnose** [comment]
That issue's been open 2 years.

**Comment by nubs** [comment]
That's unfortunate - I suppose this will work

**Comment by guywithnose** [comment]
I want to do something else eventually, but this is a good band aid for today.

**Pull request closed without merging**
